### ISSUE TITLE
Would this work on an orange pi zero 2 w?

### ISSUE THREAD

**Issue by letshin** [sonocotta/orange-pi-hi-fi-hat#2]
Would this work on an orange pi zero 2 w?

**Comment by anabolyc** [comment]
Hey @letshin . It will only work with Orange Pi due to the pinout. I'm working on the [Raspberry Pi Zero version](https://github.com/sonocotta/raspberry-media-center) currently. Please subscribe to get updated when it is ready. I hope to deliver first batch in few weeks.
